<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
	<link type="text/css" href="<?=Class_Server::extUrl()?>/reset.css" media="screen" rel="stylesheet">
	<link type="text/css" href="<?=Class_Server::libUrl()?>/template.css" media="screen" rel="stylesheet">
	
	<title><?=$this->pageTitle ?></title>
</head>

<body>
	<?php echo $this->layout()->content ?>
	
	<div class='whitebox'></div>
</body>
</html>